- https://oliveira-michel.github.io/artigos/2020/02/10/rest-api-basico---guia-visual.htm
- https://wssilva-willian.medium.com/design-de-api-rest-9807a5b16c9f
- https://fastapi.tiangolo.com/#opinions
- https://eskelsen.medium.com/estruturando-projetos-em-python-um-modelo-de-sistema-d0652d289bc
- https://docs.sqlalchemy.org/en/20/orm/session_basics.html
- https://www.youtube.com/watch?v=DdoncfOdru8&ab_channel=FernandaKipper%7CDev 